/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_drawer */

#ifndef _Included_aclasdriver_drawer
#define _Included_aclasdriver_drawer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_drawer
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_drawer_open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_drawer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_drawer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
