/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_UsbRfidModel */

#ifndef _Included_aclasdriver_UsbRfid
#define _Included_aclasdriver_UsbRfid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_UsbRfidModel
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_UsbRfid_open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_UsbRfidModel
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_UsbRfid_close
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_UsbRfidModel
 * Method:    write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_UsbRfid_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aclasdriver_UsbRfidModel
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_UsbRfid_read
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
