/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_km3_printer */

#ifndef _Included_aclasdriver_km3_printer
#define _Included_aclasdriver_km3_printer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_km3_printer
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_km3_1printer_open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_km3_printer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_km3_1printer_close
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_km3_printer
 * Method:    write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_km3_1printer_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aclasdriver_km3_printer
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_km3_1printer_read
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
