/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_printer */

#ifndef _Included_aclasdriver_printer
#define _Included_aclasdriver_printer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_printer
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_Open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_printer
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_aclasdriver_printer_Close
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_printer
 * Method:    Write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_Write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aclasdriver_printer
 * Method:    Read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_printer_Read
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_printer
 * Method:    SetContrast
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_SetContrast
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_printer
 * Method:    Feed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_Feed
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_printer
 * Method:    Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_Stop
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_printer
 * Method:    Conitnue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_Conitnue
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_printer
 * Method:    GetDotWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_GetDotWidth
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_printer
 * Method:    SetPrintMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_printer_SetPrintMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_printer
 * Method:    IsPaperExist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_aclasdriver_printer_IsPaperExist
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
