/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_SmartCard */

#ifndef _Included_aclasdriver_SmartCard
#define _Included_aclasdriver_SmartCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_SmartCard
 * Method:    Open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_SmartCard_Open
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_aclasdriver_SmartCard_Close
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    TestCardReady
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_SmartCard_TestCardReady
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    GetATR
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_SmartCard_GetATR
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    GetState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_SmartCard_GetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    IsCardRemoved
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_SmartCard_IsCardRemoved
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    SendCommand
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_SmartCard_SendCommand
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     aclasdriver_SmartCard
 * Method:    ApduCommand
 * Signature: (IIIII[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_SmartCard_ApduCommand
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
