/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasHdqApi_aclasHdqApi */

#ifndef _Included_aclasHdqApi_aclasHdqApi
#define _Included_aclasHdqApi_aclasHdqApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasHdqApi_aclasHdqApi
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_aclasHdqApi_open
  (JNIEnv *env, jobject obj);

/*
 * Class:     aclasHdqApi_aclasHdqApi
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_aclasdriver_aclasHdqApi_close
  (JNIEnv *env, jobject obj);

/*
 * Class:     aclasHdqApi_aclasHdqApi
 * Method:    read
 * Signature: ([B)V
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_aclasHdqApi_read
  (JNIEnv *env, jobject obj);

/*
 * Class:     aclasHdqApi_aclasHdqApi
 * Method:    beep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_aclasHdqApi_beep
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
