/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_rfid */

#ifndef _Included_aclasdriver_rfid
#define _Included_aclasdriver_rfid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_rfid
 * Method:    ReadCardNo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_aclasdriver_rfid_ReadCardNo
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_rfid
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_rfid_open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_rfid
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_rfid_close
  (JNIEnv *, jobject);

/*
 * Class:     Java_aclasdriver_rfid_beep
 * Method:    beep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_rfid_beep
  (JNIEnv *, jobject);


/*
 * Class:     aclasdriver_rfid
 * Method:    WriteCardBlock
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_aclasdriver_rfid_WriteCardBlock
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     aclasdriver_rfid
 * Method:    ReadCardBlock
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aclasdriver_rfid_ReadCardBlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_rfid
 * Method:    AuthKey
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_aclasdriver_rfid_AuthKey
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     aclasdriver_rfid
 * Method:    SetCardPsw
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_aclasdriver_rfid_SetCardPsw
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
