/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasMagcardApi_aclasMagcardApi */

#ifndef _Included_aclasMagcardApi_aclasMagcardApi
#define _Included_aclasMagcardApi_aclasMagcardApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasMagcardApi_aclasMagcardApi
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_aclasMagcardApi_open
  (JNIEnv *env, jobject obj);

/*
 * Class:     aclasMagcardApi_aclasMagcardApi
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_aclasdriver_aclasMagcardApi_close
  (JNIEnv *env, jobject obj);

/*
 * Class:     aclasMagcardApi_aclasMagcardApi
 * Method:    read
 * Signature: ([B)V
 */
JNIEXPORT jint JNICALL Java_aclasdriver_aclasMagcardApi_read
  (JNIEnv *env, jobject obj, jobjectArray array);

/*
 * Class:     aclasMagcardApi_aclasMagcardApi
 * Method:    beep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_aclasMagcardApi_beep
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
