/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aclasdriver_AclasLcd0 */

#ifndef _Included_aclasdriver_AclasLcd0
#define _Included_aclasdriver_AclasLcd0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_AclasLcd0_open
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_aclasdriver_AclasLcd0_close
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    writeMsg
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_aclasdriver_AclasLcd0_writeMsg
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    SetContrast
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_aclasdriver_AclasLcd0_SetContrast
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    SetBacklight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_aclasdriver_AclasLcd0_SetBacklight
  (JNIEnv *, jobject, jint);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    WriteDotMatrix
 * Signature: ([B)V
 */
JNIEXPORT jint JNICALL Java_aclasdriver_AclasLcd0_WriteDotMatrix
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    GetHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_AclasLcd0_GetWidth
  (JNIEnv *, jobject);

/*
 * Class:     aclasdriver_AclasLcd0
 * Method:    GetWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_aclasdriver_AclasLcd0_GetHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
